apiVersion: v1
kind: Pod
metadata:
  name: nginx5
  labels:
    app: nginx
spec:
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: task0-pvc
  containers:
    - image: nginx:latest
      name: nginx
      volumeMounts:
        - mountPath: /data/db
          name: persistent-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task0-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 0.5Gi
  accessModes:
    - ReadWriteOnce

