apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    app: nginx
spec:
  volumes:
    - name: index
      configMap:
        name: index-html
        items:
          - key: index.html
            path: index.html # Crea el archivo con el contenido de la clave
  containers:
    - image: nginx:latest
      name: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: index

