apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
spec:
  containers:
    - image: nginx:latest
      name: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www-volume
  volumes:
    - name: www-volume
      hostPath:
        path: /home/docker/www
        type: Directory
